id: PROD_TEMPLATE_ID
level: 2
description: Produktions-Marker Template
category: production
status: active
author: production_user
version: 1.0.0
priority: high
examples:
  - Produktions-Beispiel 1
  - Produktions-Beispiel 2
tags:
  - production
  - high-priority
validation_rules:
  - required_fields: [id, level, description]
  - id_format: "[A-Z]{1,3}_.+"
  - level_range: [1, 5]